---
title: 'Introduction to R: 02 Assessment 1'
output: 
  pdf_document: 
    fig_caption: yes
---
\pagenumbering{gobble} 
\pagenumbering{arabic} 

<!-- This is a comment, and will not be printed. 

This document should be opened from RStudio. 

In RStudio, press 'Knit' symbol -> Select 'Knit to PDF' OR 'File -> Knit Document' to convert Rmardown_template.Rmd to PDF. 

Alternatively, on console type the following:
library(rmarkdown)
rmarkdown::render("Rmarkdown_template.Rmd", output_format = "pdf_document")

Ensure the first submission is named LASTNAME_FirstInitial_A1.pdf. 
--> 

# FirstName LastName; Date
<!-- # define main sections --> 
\vspace{18pt}

1. [1 mark] In RStudio, the $\text{\underline{ANSWER}}$ tab lists the objects/variables and functions present in the current R session.
\vspace{18pt}

2. [1 mark] In RStudio, the $\text{\underline{ANSWER}}$  is where a user can give R commands and where R will show the results of a command.
\vspace{18pt}

3. [4 marks] In the below  vector called 'testVector', list the type (character, logical, integer, double, raw, complex) for each element.

``` r
# a vector containing different element types
testVector <- c("a", 1L, 1.5, TRUE)
```
"a": $\text{\underline{ANSWER}}$

1L: $\text{\underline{ANSWER}}$

1.5: $\text{\underline{ANSWER}}$

TRUE: $\text{\underline{ANSWER}}$
\vspace{18pt}

4. [1 mark] What will be the  resulting type of vector for 'testVector' from above question? 
\vspace{18pt}

5. [1 mark] What type of coercion occurs when creating the vector 'testVector'; implicit or explicit? 
\vspace{18pt}

6. [2 marks] Explain why this type of vector results for 'testVector'? Be sure to explain by outlining R coercion rules. (Hint: see 'Details' section of help documentation for \texttt{c()} function, which is for concatenation. To access help documentation, do \texttt{?c} on console.)

$\text{\underline{ANSWER:}}$
\vspace{18pt}

7. [1 mark] Look up help for R base function \texttt{mean()} using \texttt{?mean} on console. Create an integer vector called 'integerVector'. Demonstrate an applications of \texttt{mean} function using 'integerVector', i.e., provide an example of using \texttt{mean} function with 'integerVector'. Provide all your code.
\vspace{18pt}

8. [1 mark] Create the following vector called 'missingValueVector'. This vector is built using reserved term \texttt{letters}, which contain letters of the alphabet in R. Using the \texttt{c()} function, which is for concatenation, the \texttt{letters} have been combined with 3 missing values indicated by \texttt{NA}. The resulting vector is called 'missingValueVector' as shown below. How would you detect missing values in this vector called 'missingValueVector'? Provide all your code.

``` r
# vector containing missing values
missingValueVector <- c(letters, NA, NA, NA)

# autoprint the object
missingValueVector 
``` 
\vspace{18pt}

9. [2 marks] How would you identify which positions contain missing values in 'missingValueVector'? Provide all your code. (Hint: There could be multiple ways to perform this. One method is to use \texttt{which()} and \texttt{is.NA()} functions and make use of logical values).
\vspace{18pt}

10. [2 marks] Can you mix positive and negative integers simultaneously when subsetting a vector? Yes or No?$\text{\underline{  ANSWER  }}$ Justify your answer by showing one example. Provide your code for the example.
\vspace{18pt}

11. [2 marks] R comes with its own datasets, which you can access using command \texttt{data()} on the console. This will open up a new tab showing all the datasets. Pick a dataset of interest to you. Take a look at the dataset, its help documentation, and ensure it has tabular structure. How would you convert this dataset to a tibble? Provide your code.
\vspace{18pt}

12. [2 marks] A package is a way to organize code for the purpose of shareability. A package may include code, functions, documentation, tests to check package/functions and, sometimes, datasets. A repository is a place where packages are located, so users can locate, download and use them. Three of the most popular repositories for R packages are The Comprehensive R Archive Network (CRAN), Bioconductor and GitHub. 

Package \textit{covid19.analytics} is a recently developed package from Toronto, that is publicly available via both CRAN and GitHub. Note, the package may have been updated since the development of this document (finalized October, 2022). Packages are removed from CRAN if the packages violate \href{https://cran.r-project.org/web/packages/policies.html}{\textit{CRAN policies}}.

For CRAN availability of this package, see: \url{https://cran.r-project.org/web/packages/covid19.analytics/index.html}. Visit and read this page. This page will be referred to as the CRAN page for \textit{covid19.analytics} package. 

Give the commands for downloading this package from CRAN to your computer via R. Also include command to attaching the package to your current R session.
\vspace{18pt}

13. [2 marks] Let's work with some string manipulations. The \textit{tidyverse} package contain \textit{stringr} package that contains many functions for string manipulation. Use the following code to download R package \textit{protr} and create the object \texttt{P00750} as shown. Which function from \textit{stringr} R package can you use to count the number of 'G' letter occurings in \texttt{P00750}? How many 'G' letters are present? Provide all your code.  

``` r

# download and attach protr R package
install.packages("protr")
library("protr")

# attach tidyverse R package
library("tidyverse")

# attach stringr R package
library("stringr")

# to learn more about this function
?readFASTA 

# copy the example
P00750 <- readFASTA(system.file("protseq/P00750.fasta", package = "protr"))

# view object P00750
P00750

# which function from stringr package to find all occurances of G in P00750?
```
\vspace{18pt}